### ISSUE TITLE
IE11 on Win7 not supported

### ISSUE THREAD

**Issue by mygithuber** [encrypt-to/encrypt.to#37]
Hello,
"Sorry your browser is not supported. Please use Chrome >= 11, Safari >= 3.1, Firefox >= 21, Opera >= 15 or IE >= 11! " is shown if using https://encrypt.to/hello@encrypt.to with IE11-Win7-64!?
Pls refer to attached screenshot.
Perhaps there are ms specific adjustments necessary?
https://developer.mozilla.org/en-US/docs/Web/API/Window.crypto 

And really old Browsers (IE6-WinXP, FF 3.5-WinXP) do not show any warning about non compatibility of encrypt.to script.

Thx + best regards.
![ie11](https://cloud.githubusercontent.com/assets/9347903/5892672/ec935302-a4c7-11e4-9737-c3ce235f506b.jpg)

**Comment by wiegelmann** [comment]
Thanks, added workaround for IE: https://github.com/encrypt-to/encrypt.to/commit/67f21a83aca3aa1578809d7542910278a60e0a41
