### ISSUE TITLE
Sending mails via encrypt.to is not possible

### ISSUE THREAD

**Issue by HDValentin** [encrypt-to/encrypt.to#48]
When I try to send an encrypted mail via http://encrypt.to  I get the message that the email has no key on any keyserver. Even if I want to send a Mail to your Address "Sorry, diese E-Mail ist nicht auf dem Schlüsselserver hinterlegt!"

**Comment by HDValentin** [comment]
This happens in thee of four times even if I try to send a mail to mail@encrypt.to

**Comment by wiegelmann** [comment]
Sounds like the keyserver is offline, works for me. May we should improve the error message.

**Comment by wiegelmann** [comment]
duplicate #49
