### ISSUE TITLE
"This Key doesn't have any Mail Addresses"

### ISSUE THREAD

**Issue by radasbona** [encrypt-to/encrypt.to#49]
Hi,
something is wrong with encrypt.to. Every key i tried brings an error. Even your own.

(Android 7, different browsers)

**Comment by radasbona** [comment]
3 days later. It works again.

Thanks for such great communication. 😟

**Comment by HDValentin** [comment]
I think it is the same issue I had:
https://github.com/encrypt-to/encrypt.to/issues/48

**Comment by radasbona** [comment]
Ja ist es. Key Server waren aber online in den 3 Tagen.

Yes, it is. But the key server were online during these 3 days.

**Comment by HDValentin** [comment]
Yes the problem is: if the service is not reliable, the people will not use it.
Ja, wenn das nicht verlässlich ist, werden die Menschen es nicht nutzen.

**Comment by radasbona** [comment]
And it is brocken again. A Joke!

**Comment by wiegelmann** [comment]
We changed the sks-keyserver pool, seems http://ha.pool.sks-keyservers.net  was unstable in the last month.

**Comment by wiegelmann** [comment]
We found the reason, a key server in the pool changed the API, hence parsing the API response failed.

https://github.com/ctubio/php-proxy-keyserver

**Comment by radasbona** [comment]
Yes, it works. Thanks.
btw, great service. 👍
